<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'အကောင့်',
    'Account ID' => '',
    'Actual Value' => 'သင္ခန္းစာမ်ား',
    'Add' => '',
    'Add or update values by clicking on the value' => 'တန်ဖိုးအပေါ်နှိပ်ခြင်းအားဖြင့် Add သို့မဟုတ် update ကိုတန်ဖိုးများ',
    'Balance' => 'ချိန်ခွင်လျှာ',
    'Budget' => 'ဘတ်ဂျက်',
    'Budgeted Value' => 'သင္ခန္းစာမ်ား',
    'Budgets' => 'ဘတ်ဂျက်',
    'Burmese' => 'မြန်မာ',
    'Categories' => 'အမျိုးအစား',
    'Category' => 'အမျိုးအစား',
    'Category ID' => '',
    'Category successfully deleted' => '',
    'Category successfully included' => '',
    'Category updated' => '',
    'Create an account' => 'အကောင့်တစ်ခုဖန်တီးသည်',
    'Create category' => '',
    'Creating your account on Economizzer.org you agree to the terms and usage policies,' => '',
    'Current Password' => 'လက်ရှိစကားဝှu',
    'E-mail or Username' => 'အီးမေးလ်သို့မဟုတ်အသုံးပြုသူအမည်',
    'Edit Datetime' => '',
    'Email' => 'အီးမေးလ်က',
    'Entry successfully deleted' => '',
    'Entry successfully included' => '',
    'Entry updated' => '',
    'Forgot password' => 'စကားဝှက်ကိုမေ့နေပါသလား',
    'Left to budget' => 'ဘတ်ဂျက်မှ Left',
    'Login' => 'လော့ဂ်အ',
    'Login to access Micro Empire Budgeter' => 'မိုက်ခရိုအင်ပါယာဘတ်ဂျက်ရယူရဲ့ l',
    'Micro Empire Budgeter' => 'မိုက်ခရိုအင်ပါယာဘတ်ဂျက်',
    'New Password' => 'စကားဝှကိအသစ်',
    'Password' => 'စကားဝှက်ကို',
    'Please fill out the following fields to register:' => 'မှတ်ပုံတင်ရန်အောက်ပါလယ်ကွင်းဖြည့်စွက်ပေးပါ:',
    'Profile' => 'ပရိုဖိုင်းကို',
    'Register' => 'စာရင်း',
    'Remember Me' => 'ငါ့ကိုသတိရပါ',
    'Log Out' => '',
    'Submit' => 'တင်သွ',
    'The page you requested is not available or does not exist.' => '',
    'Transaction added' => '',
    'Transaction error' => '',
    'Update' => 'ကို',
    'Username' => 'အသုံးပြု',
    'Immediate Obligations' => '',
    'Rent/Mortgage' => '',
    'Groceries' => '',
    'Eletric' => '',
    'Water' => '',
    'Phone' => '',
    'Transportation' => '',
    'Interest & Fees' => '',
    'Other Expenses' => '',
    'Auto Maintenance' => '',
    'Home Maintenance' => '',
    'Insurance' => '',
    'Medical' => '',
    'Clothing' => '',
    'Gifts' => '',
    'Giving' => '',
    'Stuff I forgot to budget for' => '',
    'Savings' => '',
    'Total Savings' => '',
    'Goal / Completed' => '',
    'House Down Payment' => '',
    'Refrigerator' => '',
];
