<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 
* You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 
* If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *

 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
   
 'Account' => 'အေကာင့္',  
   
 'Actual Value' => 'သင္ခန္းစာမ်ား', 
   
 'Add or update values by clicking on the value' => 'တန္ဖိုးအေပၚ ႏွိပ္ျခင္းျဖင့္ တန္ဖိုး ကို ေပါင္းမည္ (သို႔) တန္ဖိုးကို update လုပ္မည္', 
   
 'Balance' => 'ခ်ိန္ခြင္လွ်ာ', 
   
 'Budget' => 'ဘတ္ဂ်တ္', 
   
 'Budgeted Value' => 'သင္ခန္းစာမ်ား', 
    
'Budgets' => 'ဘတ္ဂ်တ္', 
  
  'Burmese' => ' ျမန္မာ',
  
  'Categories' => 'အမ်ဳိးအစားမ်ား', 
  
  'Category' => 'အမ်ဳိးအစား', 
  
  'Category successfully deleted' => 'အမ်ဳိးအစားက႑ကို ဖ်က္လိုက္ၿပီ',
  
  'Category successfully included' => 'အမ်ဳိးအစားက႑ကို ထည့္လိုက္ၿပီ', 
   
 'Category updated' => 'အမ်ဳိးအစားက႑ကို update လုပ္ၿပီးၿပီ', 
 
   'Create an account' => 'အေကာင့္ အသစ္တစ္ခု ဖန္တီးမည္', 
  
  'Create category' => 'အမ်ဳိးအစားက႑ ဖန္တီးမည္', 
   
 'Current Password' => 'လက္ရွိ စကား၀ွက္', 
   
 'E-mail or Username' => 'အီးေမးလ္ (သို႔) အသံုးျပဳသူ အမည္', 
  
  'Edit Datetime' => 'န႔ရက္အခ်ိန္ကို ျပင္ရန္',
    'Email' => 'အီးေမးလ္', 
   
 'Forgot password' => 'စကား၀ွက္ကို ေမ့ေနပါသလား', 
  
  'Left to budget' => 'ဘတ္ဂ်တ္မွ ဘယ္ဘက္သို႔', 
   
 'Login' => '၀င္ရန္ ', 
  
  'Login to access Micro Empire Budgeter' => 'Micro Empire ရဲ႕ ဘတ္ဂ်တ္ခ်ေပးသူ app ကို ၀င္ရန္', 
    'Micro Empire Budgeter' => 'Micro Empire ဘတ္ဂ်တ္ခ်ေပးသူ app', 
    'Micro Empire Education Budgeter' => 'Micro Empire ပညာေရး ဘတ္ဂ်တ္ခ်ေပးသူ app', 
    'New Password' => 'စကား၀ွက္ အသစ္', 
    'Password' => 'စကား၀ွက္', 
    'Please fill out the following fields to register:' => 'မွတ္ပံုတင္ရန္ ေအာက္ပါ ကြက္လပ္မ်ားကို ျဖည့္ပါ', 
    'Profile' => 'ပရိုဖိုင္', 
    'Register' => 'မွတ္ပံုတင္ရန္', 
    'Remember Me' => 'ငါ့ကိုသတိရပါ', 
    'Log Out' => 'ထြက္ရန္', 
    'Submit' => ' တင္ရန္',
    'The page you requested is not available or does not exist.' => '', 
    'Update' => 'update ကို',
    'Username' => 'အသံုးျပဳသူအမည္', 
    'Immediate Obligations' => 'ခ်က္ခ်င္းေပးရမည့္ ေငြမ်ား', 
    'Rent/Mortgage' => 'အခန္းငွားခ', 
    'Groceries' => ' ေစ်း၀ယ္စရာမ်ား',
    'Electric' => 'မီတာခ', 
    'Water' => ' ေရဖိုး',
    'Phone' => 'ဖုန္းဖိုး',
    'Transportation' => 'သြားလာစရိတ္',
    'Interest & Fees' => 'အတိုးႏွင့္ စားရိတ္စက /ကုန္က်ေငြ', 
    'Other Expenses' => 'အျခား ကုန္က်ေငြမ်ား', 
    'Auto Maintenance' => 'ကား ထိန္းသိမ္းျပဳျပင္ခ', 
    'Home Maintenance' => 'အိမ္ ထိန္းသိမ္းျပဳျပင္ခ', 
    'Insurance' => 'အာမခံ', 
    'Medical' => ' ေဆးဖိုး၀ါးခ',
    'Clothing' => 'အ၀တ္အစား', 
    'Gifts' => 'လက္ေဆာင္မ်ား', 
    'Giving' => ' ေပးကမ္းျခင္း/အလွဴေငြ',
    'Stuff I forgot to budget for' => 'ဘတ္ဂ်တ္ခ်ရန္ ကၽြႏ္ုပ္ေမ့သြားေသာ အရာမ်ား', 
    'Savings' => 'စုေဆာင္းေငြ', 
    'Total Savings' => 'စုစုေပါင္း စုေငြ', 
    'Goal / Completed' => 'ပန္းတိုင္/ေရာက္ရွိၿပီး',
    'House Down Payment' => 'အိမ္အတြက္ ေပးထားေငြ', 
    'Refrigerator' => 'ရခဲေသတၱာ',
    'Log in with your Facebook Account' => 'သင့္ Facebook အေကာင့္ျဖင့္ ၀င္ရန္', 
    'Please confirm your email address by clicking the link below:' => ' ေအာက္ပါလင့္ကို ႏွိပ္ျခင္းျဖင့္ သင့္ရဲ႕ အီးေမးလ္ကို အတည္ျပဳပါ',
    'Enter how much you plan to spend in each category for the month' => 'တစ္လတြင္ ေအာက္ပါ အမ်ဳိးအစားမ်ားတစ္ခုစီအတြက္ မည္မွ် သံုးမည္ကို ရိုက္ပါ', 
    'Each time you spend money in a category, record it here' => 'အမ်ဳိးအစားတစ္ခုတြင္ သင္ေငြသံုးၿပီးတိုင္း ဤေနရာတြင္ မွတ္တမ္းတင္ပါ', 
    'January' => 'ဇန္န၀ါရီ', 
    'February' => ' ေဖေဖာ္၀ါရီ',
    'March' => 'မတ္လ', 
    'April' => 'ဧၿပီ', 
    'May' => ' ေမ',
    'June' => 'ဇြန္',
    'July' => ' ဇူလိုင္',
    'August' => 'ၾသဂုတ္',
    'September' => 'စက္တင္ဘာ', 
    'October' => ' ေအာက္တိုဘာ',
    'November' => ' ႏို၀င္ဘာ',
    'December' => 'ဒီဇင္ဘာ',
    'Savings Goals' => ' ေငြစုျခင္းအတြက္ ပန္းတိုင္မ်ား ',
    'Debt Payment Goals' => 'အေၾကြး ဆပ္ျခင္း ပန္းတိုင္မ်ား',
    'Business Loan' => 'စီးပြားေရးအတြက္ ေခ်းေငြ ',
    'Home Loan' => 'အိမ္အတြက္ ေခ်းေငြ',
    'Add Income' => '၀င္ေငြ ထပ္ထည့္ရန္',
    'Hover over question marks' => ' ေမးခြန္းသေကၤတ အေပၚတင္ျခင္းျဖင့္',
    'to see instructions' => 'အညႊန္းကို ဖတ္ပါ',
    'Goal' => 'ပန္းတိုင္',
    'Completed' => 'အဆံုးသတ္ၿပီး',
    'Current Savings' => 'လက္ရွိ စုေငြမ်ား',
    'Current Debt' => 'လက္ရွိအေၾကြး',
    'Principal' => 'မူလအေၾကြး',
    'Completed' => 'အဆံုးသတ္ၿပီး',
    'Debt Payment Goals' => 'အေၾကြးဆပ္ျခင္း ပန္းတိုင္မ်ား',
    'Business Loan' => 'စီးပြားေရးအတြက္ ေခ်းေငြ',
    'Home Loan' => 'အိမ္အတြက္ ေခ်းေငြ',
    'Data' => 'အခ်က္အလက္',
    'Description' => '‘ေဖာ္ျပခ်က္',
    'Value' => 'တန္ဖိုး',
    'Income' => '၀င္ေငြ',
    'General Income' => '‘ေယဘုယ် ၀င္ေငြ',
    'General income' => '‘ေယဘုယ် ၀င္ေငြ',
    'Debt Calculator' => 'အေၾကြး တြက္ယူျခင္း',
    'Yearly Interest Rate' => '‘ႏွစ္စဥ္ အတိုးႏႈန္း',
    'Monthly Payment' => 'လစဥ္ ေပးသည့္ေငြ',
    'Number of Payments' => 'ငြေပးသည့္ အႀကိမ္အေရအတြက္',
    'Total Payment' => 'စုစုေပါင္း ေငြေပး',
    'Total Interest' => 'စုစုေပါင္း အတိုး',
    'Enter how much you plan to save this month for each category' => 'အမ်ဳိးအစားတစ္ခုျခင္းစီအတြက္ ဤလ ေငြမည္မွ်စုမည္ကို ရိုပါ',
    'Each time you set aside money for a goal, record it here' => 'ပန္းတိုင္တစ္ခုအတြက္ ေငြဖယ္တိုင္း ဤေနရာတြင္ မွတ္တမ္းတင္ပါ',
    'Enter your amounts for each saving goal here' => 'ငြစုျခင္းပန္းတိုင္တစ္ခုစီအတြက္ ေငြပမာဏကို ရိုက္ထည့္ပါ',
    'Enter how much you plan to pay down debt this month for each category' => 'အမ်ဳိးအစားတစ္ခုျ',
    'Each time you pay down debt for a category, record it here' => 'အမ်ဳိးအစားတစ္ခုမွာ အေၾကြးေလ်ာ့ေအာင္ ဆပ္ၿပီးတိုင္း ဤေနရာမွာ မွတ္ထားပါ',
    'Enter the total principal for each debt here' => 'အေၾကြးတစ္ခုစီအတြက္ စုစုေပါင္းက်န္ေငြကို ဤေနရာမွာ ရိုက္ထည့္ပါ',
    'Are you sure you want to delete the' => 'သင္ ဒါကို ဖ်က္ရန္ ေသခ်ာပါသလား',
    'Date' => '‘ေန႔စြဲ',
    'New' => 'အသစ္',
    'Changing your email requires email confirmation' => 'သင့္အီးေမးလ္ကို ေျပာင္းလွ်င္ အီးေမးလ္ကို အတည္ျပဳရန္ လိုမည္',
    'Full Name' => 'နာမည္ အျပည့္အစံု',
'Parent Category' => 'ပင္မ အမ်ဳိးအစား',
'Sub Category' => 'အမ်ဳိးအစားအခြဲ',
'Parent or Sub Category' => 'ပင္မ သို႔ အမ်ဳိးအစားအခြဲ',
'Name' => 'အမည္',
'Loan Amount' => 'ေခ်းေငြ ပမာဏ',
'Yearly Interest rate' => 'ႏွစ္စဥ္ အတိုးႏႈန္း',
'Months to Pay' => 'ေပးရန္ လမ်ား',
'Monthly Payment' => 'လစဥ္ ေပးသည့္ ပမာဏ',
'Number of Payments' => 'ေပးသည့္ အႀကိမ္အေရအတြက္',
'Total Payment' => 'စုစုေပါင္း ေပးသည့္ ပမာဏ',
'Total Interest' => 'စုစုေပါင္း အတိုးပမာဏ',
'Results' => 'ရလဒ်များကို',
];
