<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => '',
    'Account successfully disconnected' => '',
    'Account updated' => '',
    'Can not disconnect single authentication method. Please fill email and password and try again' => '',
    'Cancel' => '',
    'Changing your email requires email confirmation' => '',
    'Create Time' => '',
    'Full Name' => '',
    'Go home' => '',
    'Go to my account' => '',
    'Guests can not disconnect accounts' => '',
    'ID' => '',
    'Instructions to reset your password have been sent' => '',
    'Invalid key' => '',
    'Language' => '',
    'Log in here' => '',
    'Password has been reset' => '',
    'Passwords do not match' => '',
    'Pending email confirmation: [ {newEmail} ]' => '',
    'Profile' => '',
    'Resend' => '',
    'Reset' => '',
    'Start Page' => '',
    'Submit' => '',
    'This account has already been connected' => '',
    'Update' => '',
    'Update Time' => '',
    'User ID' => '',
    'Yii 2 User' => '',
    'Your email [ {email} ] has been confirmed' => '',
    'or' => '',
    '{attribute} can contain only letters, numbers, and "_"' => '',
    'Сan not disconnect a foreign account' => '',
];
